[package]
name = "thumbnailer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webp = "0.2.0"
mime = "0.3.16"
thiserror = "1.0.30"
rayon = "1.5.1"

[dependencies.image]
version = "0.23.14"